name: PR Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  danger:
    name: Danger JS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install Danger
        run: npm install -g danger
      - name: Run Danger
        run: danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

  size-check:
    name: Bundle Size Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: ./doshisha-media-app/package-lock.json
      - name: Install dependencies
        working-directory: ./doshisha-media-app
        run: npm ci
      - name: Build and analyze bundle
        working-directory: ./doshisha-media-app
        run: |
          npm run build
          npx next-bundle-analyzer
        continue-on-error: true

  lighthouse:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: ./doshisha-media-app/package-lock.json
      - name: Install dependencies
        working-directory: ./doshisha-media-app
        run: npm ci
      - name: Build application
        working-directory: ./doshisha-media-app
        run: npm run build
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v11
        with:
          uploadArtifacts: true
          temporaryPublicStorage: true
          configPath: './doshisha-media-app/.lighthouserc.json'
        continue-on-error: true